title = "Alan Mendoza Sosa"
baseURL = "https://panfletx.github.io/"
disableKinds = ["taxonomy", "term"]
enableEmoji = false

[params]
  author = "Alan Mendoza Sosa"
  description = "PhD Candidate in Spanish and Portuguese, Yale University."
  avatar = "/headshot.jpg"
  email = "alan.mendozasosa@yale.edu"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 2
  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/cv"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true
