baseURL = "https://panfletx.github.io/"
title = "Alan Mendoza Sosa"
languageCode = "en"
theme = "adritian-free-hugo-theme"

[module]
[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/scss/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/vendor/bootstrap.bundle.min.js"

[[module.mounts]]
source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
target = "assets/css/bootstrap-print.css"

[params]
description = "PhD Candidate in Spanish and Portuguese, Yale University."
sections = [
  "showcase",
  "about",
  "education",
  "experience",
]
homepageExperienceCount = 6

[params.experience]
showJobCard = true

[params.plugins]
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/adritian-icons.css"
[[params.plugins.css]]
URL = "css/bootstrap-print.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
[[params.plugins.scss]]
URL = "scss/adritian.scss"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Research"
url = "/research"
weight = 2

[[menu.main]]
name = "Teaching"
url = "/teaching"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
